### ISSUE TITLE
qcloudapi-sdk-python

### ISSUE THREAD

**Issue by LiLin0637** [QcloudApi/qcloudapi-sdk-python#27]
Django==1.11.1
djangorestframework==3.7.3
python27

django 引入 qcloudapi-sdk-python 报错。
Unhandled exception in thread started by <function wrapper at 0x030A2FB0>
Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\django\utils\autoreload.py", line 227, in wrapper
    fn(*args, **kwargs)
  File "D:\Python27\lib\site-packages\django\core\management\commands\runserver.py", line 125, in inner_run
    self.check(display_num_errors=True)
  File "D:\Python27\lib\site-packages\django\core\management\base.py", line 359, in check
    include_deployment_checks=include_deployment_checks,
  File "D:\Python27\lib\site-packages\django\core\management\base.py", line 346, in _run_checks
    return checks.run_checks(**kwargs)
  File "D:\Python27\lib\site-packages\django\core\checks\registry.py", line 81, in run_checks
    new_errors = check(app_configs=app_configs)
  File "D:\Python27\lib\site-packages\django\core\checks\urls.py", line 16, in check_url_config
    return check_resolver(resolver)
  File "D:\Python27\lib\site-packages\django\core\checks\urls.py", line 26, in check_resolver
    return check_method()
  File "D:\Python27\lib\site-packages\django\urls\resolvers.py", line 254, in check
    for pattern in self.url_patterns:
  File "D:\Python27\lib\site-packages\django\utils\functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "D:\Python27\lib\site-packages\django\urls\resolvers.py", line 405, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "D:\Python27\lib\site-packages\django\utils\functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "D:\Python27\lib\site-packages\django\urls\resolvers.py", line 398, in urlconf_module
    return import_module(self.urlconf_name)
  File "D:\Python27\lib\importlib\__init__.py", line 37, in import_module
    __import__(name)
  File "E:\yohoqcloud\yohoqcloud\urls.py", line 20, in <module>
    from qcloud.views import Userinfo
  File "E:\yohoqcloud\qcloud\views.py", line 19, in <module>
    class obtainid(generics.ListAPIView):
  File "E:\yohoqcloud\qcloud\views.py", line 28, in obtainid
    value = service.call(action, params)
  File "build\bdist.win32\egg\QcloudApi\qcloudapi.py", line 169, in call
  File "build\bdist.win32\egg\QcloudApi\modules\base.py", line 157, in call
  File "build\bdist.win32\egg\QcloudApi\modules\base.py", line 134, in _build_req_inter
  File "build\bdist.win32\egg\QcloudApi\common\sign.py", line 37, in make
  File "D:\Python27\lib\hmac.py", line 136, in new
    return HMAC(key, msg, digestmod)
  File "D:\Python27\lib\hmac.py", line 75, in __init__
    self.outer.update(key.translate(trans_5C))
TypeError: character mapping must return integer, None or unicode

**Comment by QcloudApi** [comment]
请提供如下信息：
qcloudapi-sdk-python版本，可以通过pip show qcloudapi-sdk-python查看
action，params两个变量的内容
secretid
windows系统版本，32位还是64位
python27具体版本信息，如2.7.12，可以通过python --version查看

**Comment by LiLin0637** [comment]
已经解决 是由于pycharm 项目模板  from __future__ import unicode_literals 导致hmac.py 报错。注释掉即可。

**Comment by QcloudApi** [comment]
https://stackoverflow.com/questions/20849805/python-hmac-typeerror-character-mapping-must-return-integer-none-or-unicode/31572219

> As asked I'll post this as an answer. The error that you faced is a feature of Python's HMAC. It does not accept unicode. This feature is described here.
HMAC is a function which works at byte level. For this reason in Python 3 it accepts only bytes. In Python 2 we don't have bytes so it accepts only str.

**Comment by LiLin0637** [comment]
其实还是python2k与python3k之间的问题。
